# Generated by Django 3.2.7 on 2021-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=3000)),
                ('attention', models.CharField(max_length=3000)),
            ],
        ),
    ]
